import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "VET Staking FAQ: Common Questions Answered",
  description: "Get answers to frequently asked questions about VeChain staking. From minimum amounts to tax implications, we cover everything you need to know.",
  keywords: ["VET staking FAQ", "VeChain staking questions", "VET staking guide", "VTHO generation FAQ"],
  robots: { index: true, follow: true },
};

export default function VETStakingFAQ() {
  const faqs = [
    {
      question: "What is the minimum amount of VET I need to start staking?",
      answer: "It depends on the platform. Binance and Bybit allow staking from just 1 VET, while VeChain StarGate requires a minimum of 10,000 VET. For native wallet staking (VTHO generation), there is no minimum - you can stake any amount."
    },
    {
      question: "How often are staking rewards distributed?",
      answer: "Most platforms distribute rewards daily. Binance typically distributes around 00:00 UTC, while Bybit distributes throughout the day. Native VTHO generation is continuous - you earn VTHO every second you hold VET."
    },
    {
      question: "Can I unstake my VET anytime?",
      answer: "This depends on whether you choose flexible or locked staking. Flexible staking (like Binance's simple earn) allows you to withdraw anytime, usually within 24-48 hours. Locked staking products have specific lock-up periods ranging from 30 to 90 days."
    },
    {
      question: "What's the difference between staking VET and holding VET?",
      answer: "All VET holders automatically generate VTHO at the base rate of 0.000432 VTHO per VET per day (~0.5% APY). 'Staking' on platforms like Binance provides enhanced rewards (1.2-1.63% APY) in exchange for keeping your VET on their platform."
    },
    {
      question: "Are VET staking rewards taxable?",
      answer: "In most jurisdictions, yes. Staking rewards are typically considered income and taxed accordingly. The exact treatment varies by country. Consult a tax professional familiar with cryptocurrency in your jurisdiction for specific guidance."
    },
    {
      question: "What are the risks of staking VET?",
      answer: "Main risks include: (1) Platform risk - exchanges could be hacked or become insolvent, (2) Market risk - VET price could drop, negating staking gains, (3) Lock-up risk - unable to sell during market downturns if VET is locked, (4) Opportunity cost - potentially missing better investment opportunities."
    },
    {
      question: "Which platform offers the best VET staking APY?",
      answer: "As of December 2025, Binance offers the highest verified APY at 1.63%, followed by VeChain StarGate at 1.5%+ and Bybit at approximately 1.2%. These rates can change, so always verify current rates before staking."
    },
    {
      question: "Do I need to claim my staking rewards manually?",
      answer: "On most platforms like Binance and Bybit, rewards are automatically credited to your account daily - no manual claiming required. For native VTHO generation, VTHO automatically accumulates in your wallet."
    },
    {
      question: "Can I stake VET if I'm in the United States?",
      answer: "Availability varies by platform and state. Some platforms have restrictions for US users. Check each platform's terms of service and ensure compliance with local regulations. VeChain native wallet staking (VTHO generation) is available globally."
    },
    {
      question: "What happens to my staking rewards if VET price drops?",
      answer: "You still earn the same percentage APY in VET terms. However, the USD value of your rewards will decrease if VET price drops. For example, earning 163 VET/year is worth $1.75 at $0.0107/VET but only $0.815 if VET drops to $0.005."
    },
    {
      question: "Is VeChain staking safe?",
      answer: "Staking on reputable exchanges like Binance is generally safe, but not without risk. For maximum security, consider splitting your VET between exchange staking (higher yields) and self-custody native wallet (full control). Never stake more than you can afford to lose."
    },
    {
      question: "How is VTHO generated from VET?",
      answer: "VTHO is automatically generated by the VeChain blockchain at a rate of 0.000432 VTHO per VET per day. This is a continuous process - you don't need to do anything except hold VET in a compatible wallet. Enhanced staking rates on exchanges are additional rewards provided by those platforms."
    },
    {
      question: "Can I lose my VET while staking?",
      answer: "Your VET itself is not at risk from the staking process. However, you could lose VET if: (1) The exchange is hacked or becomes insolvent, (2) You fall for a phishing scam, (3) You use an unsecure wallet. Always use reputable platforms and enable all security features."
    },
    {
      question: "What's the difference between APY and APR for staking?",
      answer: "APY (Annual Percentage Yield) includes compound interest - assuming you reinvest rewards. APR (Annual Percentage Rate) does not include compounding. Most platforms display APY. For VET staking, the difference is minimal unless you actively reinvest rewards."
    },
    {
      question: "Do I need KYC verification to stake VET?",
      answer: "For centralized exchanges like Binance and Bybit, yes - KYC (Know Your Customer) verification is required. For native wallet staking (self-custody), no KYC is needed. You simply hold VET in your VeChainThor wallet and automatically generate VTHO."
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      <header className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <Link href="/" className="flex items-center space-x-3">
            <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-lg flex items-center justify-center">
              <span className="text-white font-bold text-xl">V</span>
            </div>
            <div><h1 className="text-2xl font-bold text-gray-900">VeChain Staking Calculator</h1><p className="text-sm text-gray-500">Blog</p></div>
          </Link>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <article className="bg-white rounded-2xl shadow-xl p-8 md:p-12">
          <nav className="text-sm text-gray-500 mb-6">
            <Link href="/">Home</Link> › <Link href="/blog">Blog</Link> › <span className="text-gray-900">VET Staking FAQ</span>
          </nav>

          <div className="mb-8">
            <span className="inline-block px-3 py-1 bg-gray-100 text-gray-800 text-xs font-semibold rounded-full mr-3">FAQ</span>
            <span className="text-sm text-gray-500">December 17, 2025 • 4 min read</span>
            <h1 className="text-4xl font-extrabold text-gray-900 mt-4 mb-4">VET Staking FAQ: Common Questions Answered</h1>
            <p className="text-xl text-gray-600">Everything you need to know about VeChain staking, answered in one place.</p>
          </div>

          <div className="prose prose-lg max-w-none">
            <p className="text-gray-700 leading-relaxed mb-8">Whether you're new to VeChain staking or looking to optimize your strategy, this FAQ covers the most common questions we receive. Can't find your answer? <Link href="/contact" className="text-blue-600 hover:underline">Contact us</Link>.</p>

            <div className="space-y-4">
              {faqs.map((faq, index) => (
                <details key={index} className="group bg-gray-50 rounded-lg">
                  <summary className="flex justify-between items-center cursor-pointer list-none p-6 hover:bg-gray-100 rounded-lg transition-colors">
                    <span className="font-semibold text-gray-900 pr-4">{faq.question}</span>
                    <span className="transition group-open:rotate-180 flex-shrink-0">
                      <svg className="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
                      </svg>
                    </span>
                  </summary>
                  <div className="px-6 pb-6">
                    <p className="text-gray-700 leading-relaxed">{faq.answer}</p>
                  </div>
                </details>
              ))}
            </div>

            <div className="bg-blue-50 border-l-4 border-blue-500 p-6 my-8">
              <h3 className="font-bold text-blue-900 mb-2">Still Have Questions?</h3>
              <p className="text-sm text-blue-800 mb-4">We're here to help! Reach out through our contact page or check out our other guides:</p>
              <div className="flex flex-wrap gap-3">
                <Link href="/blog/vechain-staking-guide" className="text-blue-600 hover:underline text-sm font-medium">
                  Complete Staking Guide →
                </Link>
                <Link href="/blog/binance-vet-staking-tutorial" className="text-blue-600 hover:underline text-sm font-medium">
                  Binance Tutorial →
                </Link>
                <Link href="/contact" className="text-blue-600 hover:underline text-sm font-medium">
                  Contact Us →
                </Link>
              </div>
            </div>

            <div className="bg-gradient-to-r from-blue-500 to-indigo-600 rounded-xl p-8 text-center text-white my-8">
              <h3 className="text-2xl font-bold mb-4">Ready to Start Staking?</h3>
              <p className="text-blue-100 mb-6">Calculate your potential VET staking rewards now</p>
              <Link href="/" className="inline-block px-8 py-3 bg-white text-blue-600 font-semibold rounded-lg hover:bg-blue-50 transition-colors">
                Use Calculator
              </Link>
            </div>
          </div>
        </article>
      </main>

      <footer className="bg-white mt-16 border-t border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <p className="text-center text-gray-500 text-sm">© 2025 VET Staking Calculator. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
